---
# tasks file for roles/common
- name: Update all system packages (via yum command — module not suitable)
  ansible.builtin.command: yum update -y
  when: ansible_os_family == "RedHat"
  changed_when: true
  tags: skip_ansible_lint

- name: Update apt packages (Ubuntu / Debian)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - git
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy setup script (optional)
  ansible.builtin.copy:
    src: files/setup.sh
    dest: /tmp/setup.sh
    mode: '0755'

- name: Run setup script
  ansible.builtin.command: /tmp/setup.sh
  when: ansible_os_family == "RedHat"
  changed_when: true
