---
# tasks file for roles/common
- name: Update all system packages (via yum command — module not suitable)
  ansible.builtin.command: yum update -y
  when: ansible_os_family == "RedHat"
  changed_when: true
  tags: skip_ansible_lint

- name: Update apt packages (Ubuntu / Debian)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - git
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Docker on Amazon Linux 2023
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"
  block:
    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Enable and start Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

#- name: Ensure docker SDK for Python is present
#  ansible.builtin.pip:
#    name: docker
#  become: true

- name: Create shared docker network
  community.docker.docker_network:
    name: "{{ llm_docker_network }}"
    state: present
