---
# GHCR: login, pull, run

- name: Docker login to GHCR (using PAT)
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ ghcr_username }}"
    password: "{{ ghcr_token }}"
  become: true
  no_log: true

# Example image value:
#   llm_api_image: "ghcr.io/{{ ghcr_owner }}/llm-api-server:latest"
- name: Pull llm-api image from GHCR (force refresh even for same tag)
  community.docker.docker_image:
    name: "{{ llm_api_image }}"
    source: pull
    force_source: true
  register: llm_api_pull
  become: true

- name: Run/Recreate llm-api container when image changed
  community.docker.docker_container:
    name: llm-api
    image: "{{ llm_api_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ llm_docker_network }}"
    ports:
      - "{{ expose_llm_api_port }}:8000"
    env:
      OPENAI_API_KEY: "{{ openai_api_key }}"
      OLLAMA_HOST: "{{ ollama_host }}"
    recreate: "{{ llm_api_pull.changed }}"
    pull: false
  become: true
