name: Auto Shutdown EC2

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  shutdown:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION || 'ca-central-1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install boto3

      - name: Run EC2 Shutdown Script
        run: |
          python3 ec2_utils/ec2_autoshutdown.py --region "$AWS_DEFAULT_REGION"
