name: Unified CI

on: [push, pull_request]

jobs:
  terraform:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
      - uses: terraform-linters/setup-tflint@v1
      - run: |
          tflint --init
          tflint

  ansible:
    name: Ansible Lint & Syntax Check
    runs-on: ubuntu-latest
    needs: terraform  # 👈 run after terraform job finishes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install --upgrade pip
          pip install ansible ansible-lint yamllint
      - run: |
          find ansible -name "*.yml" | while read f; do
            echo "Checking syntax for $f"
            ansible-playbook --syntax-check -i ansible/inventory/hosts.yaml "$f"
          done
      - run: ansible-lint ansible
      - run: yamllint -c .yamllint.yaml ansible/

  python:
    name: Python Lint & Test
    runs-on: ubuntu-latest
    needs: ansible  # 👈 runs after ansible finishes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pip install flake8 pytest
          flake8 .
          pytest
